url: https://www.braedenalford.com
#baseurl: /agency-jekyll-theme/

# Site settings
title: Braeden Alford
email: braeden.w.alford@gmail.com
description: "Data Scientist"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/braedenalford/
  - title: github
    url: https://github.com/braedenalford
  - title: email
    url: mailto:braeden.w.alford@gmail.com


# Build settings
markdown: kramdown
permalink: pretty
